name: dimension_reduction
channels:
  - conda-forge
  - pyviz
dependencies:
  - flake8
  - sphinx
  - click
  - coverage
  - awscli
  - python-dotenv>=0.5.1
  - python=3
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - nb_conda
  - pytest
  - hypothesis
  - nbval
  - nbdime
  - imageio
  - opencv
  - umap-learn
  - bokeh>=0.13.0
  - joblib
  - pip>=9
  - pyviz
  - cmake
  - pip:
    - -e .
    - pytest-cov
    - git+https://github.com/acwooding/Multicore-TSNE.git@add-repr
    - coveralls
