name: dimension_reduction
channels:
  - conda-forge
dependencies:
  - flake8
  - sphinx
  - click
  - coverage
  - awscli
  - python-dotenv>=0.5.1
  - python=3
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - nb_conda
  - pytest
  - hypothesis
  - nbval
  - nbdime
  - imageio
  - opencv
  - umap-learn
  - pip
  - pip:
    - -e .
